name: "Update README"
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.24'
      - uses: actions/checkout@v7
      - run: go install github.com/muesli/markscribe@master
      - run: markscribe -write README.md templates/README.md.tpl
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: "Import GPG key"
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          
      - name: "Update generated README"
        uses: stefanzweifel/git-auto-commit-action@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
           commit_user_name: ${{ steps.import-gpg.outputs.name }}
           commit_user_email: ${{ steps.import-gpg.outputs.email }}
           commit_message: 'Update generated README'
           commit_options: '-S --amend --no-edit'
           push_options: '--force'
           skip_fetch: true
